# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xa7a100tcsg324-1I

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/FloreaTudor/mipsfinalPC/mipsfinalPC.cache/wt [current_project]
set_property parent.project_path D:/FloreaTudor/mipsfinalPC/mipsfinalPC.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/FloreaTudor/mipsfinalPC/mipsfinalPC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/FloreaTudor/mipsfinalPC/mipsfinalPC.srcs/sources_1/new/reg_file.vhd
  D:/FloreaTudor/mipsfinalPC/mipsfinalPC.srcs/sources_1/new/ssdEn.vhd
  D:/FloreaTudor/mipsfinalPC/mipsfinalPC.srcs/sources_1/new/mpg.vhd
  D:/FloreaTudor/mipsfinalPC/mipsfinalPC.srcs/sources_1/new/main_control.vhd
  D:/FloreaTudor/mipsfinalPC/mipsfinalPC.srcs/sources_1/new/InstructionFetch.vhd
  D:/FloreaTudor/mipsfinalPC/mipsfinalPC.srcs/sources_1/new/InstructionDecode.vhd
  D:/FloreaTudor/mipsfinalPC/mipsfinalPC.srcs/sources_1/new/executionUnit.vhd
  D:/FloreaTudor/mipsfinalPC/mipsfinalPC.srcs/sources_1/new/dataPath.vhd
  D:/FloreaTudor/mipsfinalPC/mipsfinalPC.srcs/sources_1/new/main.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/FloreaTudor/mipsfinalPC/utcn-ca-nexys-a7-100t.xdc
set_property used_in_implementation false [get_files D:/FloreaTudor/mipsfinalPC/utcn-ca-nexys-a7-100t.xdc]


synth_design -top main -part xa7a100tcsg324-1I


write_checkpoint -force -noxdef main.dcp

catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
