DATA SEGMENT PARA PUBLIC 'DATA'
    VAR1    DW  1256H
    VAR2    DW  0ABCDH
    VAR3    DD  0
DATA ENDS

CODE SEGMENT PARA PUBLIC 'CODE'
ASSUME CS:CODE, DS:DATA
START PROC FAR
PUSH DS
XOR AX, AX
MOV DS, AX
PUSH AX
MOV AX, DATA
MOV DS, AX
; your code starts here

PUSH VAR2
PUSH VAR1
POP WORD PTR VAR3[0]
POP WORD PTR VAR3[2]

; your code ends here
RET
START ENDP

CODE ENDS
END START