DATA SEGMENT PARA PUBLIC 'DATA'
    TBL     DB  '0123456789ABCDEF'
    VAR1    DB  0AH
    VAR2    DW  0
    VAR3    DD  0
    VAR4    DD  0
    VAR     DW  12ABH
    VAR_STRING DB 4 DUP(0)
DATA ENDS

CODE SEGMENT PARA PUBLIC 'CODE'
ASSUME CS:CODE, DS:DATA
START PROC FAR
PUSH DS
XOR AX, AX
MOV DS, AX
PUSH AX
MOV AX, DATA
MOV DS, AX
; your code starts here

MOV AL,VAR1
MOV BYTE PTR VAR2[1],AL
MOV BYTE PTR VAR2[0],1EH

MOV AX,0
MOV AX,VAR2
MOV WORD PTR VAR3[1],AX
MOV BYTE PTR VAR3[0],0FBH
MOV AL,VAR1
MOV BYTE PTR VAR3[2],AL

;ex2

PUSH VAR2
PUSH 1BCEH
POP WORD PTR VAR4[0] 
POP WORD PTR VAR4[2]

;ex3

MOV DI,0
MOV SI,0
MOV AL,010H
MOV BX,OFFSET TBL
XLAT TBL 
MOV DL, BYTE PTR VAR[SI]
SHR DX,4
AND DL,0FH
MOV AL,DL      
MOV BX,OFFSET TBL
XLAT TBL 
MOV VAR_STR[DI],AL
INC DI
MOV DL, BYTE PTR VAR[SI]
AND DL,0FH
MOV AL,DL      
MOV BX,OFFSET TBL
XLAT TBL 
MOV VAR_STR[DI],AL
INC DI
INC SI

; your code ends here
RET
START ENDP

CODE ENDS
END START